[package]
name = "vk_users_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
rvk = "0.21.0"
serde = "1.0.133"
serde_json = "1.0.74"
mongodb = "2.0.0"